version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mqtt-broker/config:/mosquitto/config
      - ./mqtt-broker/auth:/etc/mosquitto/
     #- ./mqtt-broker/certs:/mosquitto/certs
    expose:
      - "1883"
      - "8883"
      - "9001"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"

  server-web-mqtt-client:
    image: httpd:2.4
    volumes:
      - ./web-mqtt-client:/usr/local/apache2/htdocs/
    ports:
      - "5001:80"


# networks:
#   mq-connection-network:
#     driver:                 bridge